### ISSUE TITLE
Error: logWarnFn is not a function

### ISSUE THREAD

**Issue by bjclopes** [BlinkTagInc/transit-departures-widget#13]
Hello there,

Not sure if it's an issue with this project or only with one of its dependencies.
I got the following error while trying to run "transit-departures-widget".
I installed it globally via npm.

Error: logWarnFn is not a function
  TypeError: logWarnFn is not a function
 
  - i18n.js:1378 logWarn
    [lib]/[transit-departures-widget]/[i18n]/i18n.js:1378:5
  
  - i18n.js:957 translate
    [lib]/[transit-departures-widget]/[i18n]/i18n.js:957:7
  
  - i18n.js:285 Object.i18nTranslate [as __]
    [lib]/[transit-departures-widget]/[i18n]/i18n.js:285:13
  
  - transit-departures-widget.js:204 getDirectionsForRoute
    [lib]/[transit-departures-widget]/dist/bin/transit-departures-widget.js:204:25
  
  - transit-departures-widget.js:288 generateTransitDeparturesWidgetJson
    [lib]/[transit-departures-widget]/dist/bin/transit-departures-widget.js:288:24
  
  - transit-departures-widget.js:427 transitDeparturesWidget
    [lib]/[transit-departures-widget]/dist/bin/transit-departures-widget.js:427:29
  
  - transit-departures-widget.js:469 async setupImport
    [lib]/[transit-departures-widget]/dist/bin/transit-departures-widget.js:469:3

If it's helpful, I'm using the following transportation agency urls:
GTFS: https://gateway.carris.pt/gateway/gtfs/api/v2.11/GTFS
GTFS-RT feed: https://gateway.carris.pt/gateway/gtfs/api/v2.11/GTFS/realtime/vehiclepositions

Thanks.

**Comment by brendannee** [comment]
Thanks for reporting this.

I just pushed an update which fixes this and a few other issues when running transit-departures-widget as a globally installed npm package: https://github.com/BlinkTagInc/transit-departures-widget/releases/tag/2.5.0

Try the latest version and let me know if you need any errors.
